### ISSUE TITLE
Can you share erogamescape_sql_output.zip

### ISSUE THREAD

**Issue by juefeix** [shaform/GirlsManifold#2]
Hi, I was wondering if you could share erogamescape_sql_output.zip? I was trying to use your code to crawl the images but it seems that erogamescape_sql_output.zip is missing.

Thanks.

best,
Felix

**Comment by shaform** [comment]
@juefeix Sure, it's here: https://github.com/makegirlsmoe/makegirlsmoe_web/issues/11#issuecomment-330504682
